from __future__ import annotations

TARGETS = [
    {
        "platform_id": "linux-x64-musl",
        "target": "x86_64-unknown-linux-musl",
        "artifact_binary": "openclash",
        "package_binary": "openclash",
        "npm_package": "openclash-bin-linux-x64-musl",
        "npm_os": "linux",
        "npm_cpu": "x64",
        "python_package": "openclash-bin-linux-x64-musl",
        "python_module": "openclash_bin_linux_x64_musl",
        "python_marker": "platform_system == 'Linux' and platform_machine == 'x86_64'",
    },
    {
        "platform_id": "linux-arm64-musl",
        "target": "aarch64-unknown-linux-musl",
        "artifact_binary": "openclash",
        "package_binary": "openclash",
        "npm_package": "openclash-bin-linux-arm64-musl",
        "npm_os": "linux",
        "npm_cpu": "arm64",
        "python_package": "openclash-bin-linux-arm64-musl",
        "python_module": "openclash_bin_linux_arm64_musl",
        "python_marker": "platform_system == 'Linux' and (platform_machine == 'aarch64' or platform_machine == 'arm64')",
    },
    {
        "platform_id": "darwin-arm64",
        "target": "aarch64-apple-darwin",
        "artifact_binary": "openclash",
        "package_binary": "openclash",
        "npm_package": "openclash-bin-darwin-arm64",
        "npm_os": "darwin",
        "npm_cpu": "arm64",
        "python_package": "openclash-bin-darwin-arm64",
        "python_module": "openclash_bin_darwin_arm64",
        "python_marker": "platform_system == 'Darwin' and platform_machine == 'arm64'",
    },
    {
        "platform_id": "win32-ia32",
        "target": "i686-pc-windows-msvc",
        "artifact_binary": "openclash.exe",
        "package_binary": "openclash.exe",
        "npm_package": "openclash-bin-win32-ia32",
        "npm_os": "win32",
        "npm_cpu": "ia32",
        "python_package": "openclash-bin-win32-ia32",
        "python_module": "openclash_bin_win32_ia32",
        "python_marker": "platform_system == 'Windows' and (platform_machine == 'x86' or platform_machine == 'i386' or platform_machine == 'i686')",
    },
]
